### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by alexjago**
Add styling to match https://bestmotherfucking.website/

### CODE REVIEW

**Comment by yaakov-h** [comment]
That bot on #2 looks somewhat annoying.

I definitely prefer this styling, but I think the max-width needs to be a little wider. With these changes, the embedded Google Doc requires horizontal scrolling.

You can view that [here](https://deploy-preview-1--covidsafe-watch.netlify.app/).

**Comment by alexjago** [comment]
> I definitely prefer this styling, but I think the max-width needs to be a little wider. With these changes, the embedded Google Doc requires horizontal scrolling.
> 
> You can view that [here](https://deploy-preview-1--covidsafe-watch.netlify.app/).

Excellent point. I'll see about adjusting it.

**Review by ghuntley — APPROVED** [review]
Hell yeah

**Comment by ghuntley** [comment]
Just keep PRing ♥️ welcome to the wild west of pancake opensource.

**Pull request merged**
